# -----
# output-duct-options:
# You can slightly lower these if output duct timings are too high
# -----
# max-duct-length:
# maximum length of a duct network which is comprised of item ducts and output ducts, minimum 4
# default: 12
# -----
# max-input-inventories:
# maximum number of input inventories or machine menus to check, minimum 1
# default: 8
# -----
# max-slots-to-check:
# maximum slots to check in each input inventories (it takes longer to check all 54 slots of a chest for ex), minimum 1
# default: 9
# -----
# infinity-enchant-levels:
# levels of infinity gear. this will not affect existing items. adding more enchants wont have any effect, only change levels. 
# keep in mind protection levels past 5 are purely visual.
# -----
output-duct-options:
  max-duct-length: 12
  max-input-inventories: 8
  max-slots-to-check: 9
infinity-enchant-levels:
  blade:
    sharpness: 20
    looting: 10
    fire-aspect: 10
  pickaxe:
    efficiency: 40
    fortune: 20
  shovel: 
    efficiency: 40
    silk-touch: 10
  axe:
    efficiency: 40
    sharpness: 20
    fire-aspect: 10
    looting: 0
    silk-touch: 0
  bow:
    power: 10
    flame: 10
    infinity: 10
    punch: 0
  crown:
    protection: 40
    aqua-affinity: 10
  chestplate:
    protection: 40
    thorns: 10
  leggings:
    protection: 40
    thorns: 10
  boots:
    protection: 40
    feather-falling: 0
    thorns: 0
  shield:
    protection: 40
    thorns: 10