name: InfinityExpansion
author: Mooy1
description: more slimefun content
main: me.mooy1.infinityexpansion.InfinityExpansion
website: https://github.com/Mooy1/InfinityExpansion
depend: [Slimefun]
version: ${project.version}
api-version: 1.16

commands:
  infinityexpansion:
    description: Do /infinityexpansion help for a list of commands
    usage: /<command> <subcommand>
    aliases: [ie, ix, infinity]

permissions:
  infinityexpansion.admin:
    description: InfinityExpansion admin commands
    default: op