name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: InfinityExpansion.jar
        path: staging
    - name: Automatic Releases
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "exp"
        prerelease: true
        title: "Automatic Releases"
        files: |
          target/*.jar
